services:
  postgres:
    image: postgres:latest
    container_name: DB-for-JPA
    restart: unless-stopped
    environment:
      POSTGRES_DB: db-for-jpa
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5434:5432"
