spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/db-for-jpa
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

testdata:
  userCount: 10
  artistCount: 10
  albumCount: 100
  purchaseCount: 1000
  songCount: 100